const crypto = require("crypto");
const fs = require("fs");
const tok = fs.readFileSync(process.argv[2], "utf8").trim();
const params0 = { user: JSON.stringify({ id: 777000555, username: "e2e_miniapp", first_name: "E2E" }), auth_date: "1726000000" };
const dcs = Object.keys(params0).sort().map((k) => k + "=" + params0[k]).join("&");
const secret = crypto.createHmac("sha256", "WebAppData").update(tok).digest();
const h = crypto.createHmac("sha256", secret).update(dcs).digest("hex");
const init_data = dcs + "&hash=" + h;
console.log("token len:", tok.length, "| token head:", tok.slice(0, 12));
const params = new URLSearchParams(init_data);
const hash = String(params.get("hash") || "");
params.delete("hash");
params.delete("signature");
const dcs2 = [...params.entries()].map(([k, v]) => k + "=" + v).sort().join("&");
const secret2 = crypto.createHmac("sha256", "WebAppData").update(tok).digest();
const calc = crypto.createHmac("sha256", secret2).update(dcs2).digest("hex");
console.log("hash==calc:", hash === calc);
console.log("dcs==dcs2:", dcs === dcs2);
const u = JSON.parse(params.get("user") || "{}");
console.log("username:", u.username);
